# Generated by Django 4.1.3 on 2022-12-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='participants',
        ),
    ]
